class DishMode:
    STANDARD = 'STANDARD'
    CONSTRUCTOR = 'CONSTRUCTOR'


class CategoryCode:
    FIRST = 'FIRST'
    SECOND_STANDARD = 'SECOND_STANDARD'
    SECOND_CONSTRUCTOR_MAIN_PART = 'SECOND_CONSTRUCTOR_MAIN_PART'
    SECOND_CONSTRUCTOR_SIDE_PART = 'SECOND_CONSTRUCTOR_SIDE_PART'
    VEGAN = 'VEGAN'
