import datetime


class DishMode:
    STANDARD = 'STANDARD'
    CONSTRUCTOR = 'CONSTRUCTOR'


class CategoryCode:
    FIRST = 'FIRST'
    SECOND_STANDARD = 'SECOND_STANDARD'
    SECOND_CONSTRUCTOR_MAIN_PART = 'SECOND_CONSTRUCTOR_MAIN_PART'
    SECOND_CONSTRUCTOR_SIDE_PART = 'SECOND_CONSTRUCTOR_SIDE_PART'
    VEGAN = 'VEGAN'


DEADLINE_TIME = datetime.time(19, 00, 00)
